<?php
/**
 * NsfwResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NsfwResultTest Class Doc Comment
 *
 * @category    Class */
// * @description The result of scanning a video file for NSFW content
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NsfwResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NsfwResult"
     */
    public function testNsfwResult()
    {
    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {
    }

    /**
     * Test attribute "highest_classification_result"
     */
    public function testPropertyHighestClassificationResult()
    {
    }

    /**
     * Test attribute "highest_score"
     */
    public function testPropertyHighestScore()
    {
    }

    /**
     * Test attribute "total_racy_frames"
     */
    public function testPropertyTotalRacyFrames()
    {
    }

    /**
     * Test attribute "total_nsfw_frames"
     */
    public function testPropertyTotalNsfwFrames()
    {
    }

    /**
     * Test attribute "total_frames"
     */
    public function testPropertyTotalFrames()
    {
    }

    /**
     * Test attribute "nsfw_scanned_frames"
     */
    public function testPropertyNsfwScannedFrames()
    {
    }
}
