<?php
/**
 * AudioApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AudioApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AudioApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for audioConvertToAac
     *
     * Convert Audio File to AAC format..
     *
     */
    public function testAudioConvertToAac()
    {
    }

    /**
     * Test case for audioConvertToM4a
     *
     * Convert Audio File to M4A format..
     *
     */
    public function testAudioConvertToM4a()
    {
    }

    /**
     * Test case for audioConvertToMp3
     *
     * Convert Audio File to MP3 format..
     *
     */
    public function testAudioConvertToMp3()
    {
    }

    /**
     * Test case for audioConvertToWav
     *
     * Convert Audio File to WAV format..
     *
     */
    public function testAudioConvertToWav()
    {
    }
}
