<?php
/**
 * VideoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * VideoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VideoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for videoConvertToGif
     *
     * Convert Video to Animated GIF format..
     *
     */
    public function testVideoConvertToGif()
    {
    }

    /**
     * Test case for videoConvertToMov
     *
     * Convert Video to MOV format..
     *
     */
    public function testVideoConvertToMov()
    {
    }

    /**
     * Test case for videoConvertToMp4
     *
     * Convert Video to MP4 format..
     *
     */
    public function testVideoConvertToMp4()
    {
    }

    /**
     * Test case for videoConvertToStillFrames
     *
     * Convert Video to PNG Still Frames..
     *
     */
    public function testVideoConvertToStillFrames()
    {
    }

    /**
     * Test case for videoConvertToWebm
     *
     * Convert Video to WEBM format..
     *
     */
    public function testVideoConvertToWebm()
    {
    }

    /**
     * Test case for videoCutVideo
     *
     * Cut a Video to a Shorter Length.
     *
     */
    public function testVideoCutVideo()
    {
    }

    /**
     * Test case for videoGetInfo
     *
     * Get detailed information about a video or audio file.
     *
     */
    public function testVideoGetInfo()
    {
    }

    /**
     * Test case for videoResizeVideo
     *
     * Resizes a Video Preserving the Original Aspect Ratio..
     *
     */
    public function testVideoResizeVideo()
    {
    }

    /**
     * Test case for videoResizeVideoSimple
     *
     * Resizes a Video without Preserving Aspect Ratio..
     *
     */
    public function testVideoResizeVideoSimple()
    {
    }

    /**
     * Test case for videoScanForNsfw
     *
     * Scan a Video for NSFW content..
     *
     */
    public function testVideoScanForNsfw()
    {
    }

    /**
     * Test case for videoSplitVideo
     *
     * Split a Video into Two Shorter Videos.
     *
     */
    public function testVideoSplitVideo()
    {
    }
}
